### ISSUE TITLE
Block Puzzle Dialogue Loop

### ISSUE THREAD

**Issue by julieraptor** [witchslabyrinth/WitchsLabyrinthGame#137]
Branch: Dev
- During the block puzzle, pressing E starts/keeps restarting dialogue with evil Oli whether or not you solved the puzzle, and the block you're using clips through the table endlessly

1. I did the Liars puzzle first here. I didn't solve the block puzzle but pressed E to see if I could exit 
2. Pressing E will not speed up the dialogue, it will just restart from the beginning
3. When you go to the pond to interact with fish after pressing E to go into Block dialogue it takes you back to Block dialogue. After the cutscene you'll still be in the pond
4. Pressing E anywhere/any other interaction including the Block puzzle itself triggers the Block puzzle cutscene

**Comment by dmg9626** [comment]
This happens with the Zodiac Puzzle too! It brings up a different dialogue conversation though (the one with whats his name, the mysterious ukiyo-e guy). 

It's probably the same issue though, something with Victor's Yarnspinner code I imagine.

**Comment by cptvictor** [comment]
Been fixed for a while, just gotta merge the pr I just linked
