### ISSUE TITLE
Footsteps turn off after interacting with anything

### ISSUE THREAD

**Issue by maggiejmay** [witchslabyrinth/WitchsLabyrinthGame#184]
### Description
Oliver will no longer have footsteps once he interacts with anything, the cat will keep the footsteps sounds though. Have not had the footsteps come back once they are gone, by switching camera/character/pausing/ or solving puzzles

### Branch

Develop 

### Steps to Reproduce

1. Walk anywhere
2. Interact with anything that has the "e to interact"
3. Exit out
4. Walk around as Oliver

**Comment by dmg9626** [comment]
fixed bug in Audio_Submission
